### ISSUE TITLE
Cannot compile it

### ISSUE THREAD

**Issue by G0ne** [cgfandia/windep#7] opened 2023-08-21 17:59 UTC
Software used: VS2022 community edition
OS: windows 10

Error:
![image](https://github.com/cgfandia/windep/assets/87523421/499d364b-7f1a-49c3-b35b-1193fef1109c)

**Comment by cgfandia** [comment] 2023-08-22 09:51
I can't reproduce it on clean setup.
Try to disable clang-tidy in project properties:
Configuration Properties - Code Analysis - General - Enable Clang-Tidy - No

**Comment by G0ne** [comment] 2023-08-22 17:16
It works!! thanks!(:
Btw, i have 2 more questions: 

1) Why does it happen?
[-] Cannot open 'c:\path\to\some.exe' image

2) Can you please explain what does the option '-d'?

**Comment by cgfandia** [comment] 2023-08-22 17:27
> It works!! thanks!(: Btw, i have 2 more questions:
> 
> 1. Why does it happen?
>    [-] Cannot open 'c:\path\to\some.exe' image - it is not an issue about permissions because i can run it
> 2. Can you please explain what does the option '-d'?

1. Maybe architecture of the image and windep.exe is different, x86 vs x64. It should be the same.
2. This flag enables resolving of delayed imports. 

> A delay-load DLL is a DLL that is implicitly linked but not actually loaded until your code attempts to reference a symbol contained within the DLL.

**Comment by G0ne** [comment] 2023-08-22 18:11
yeah, i figured it out, i just wanted to be sure in case there was an unexpected error(:
last thing and i hope i won't annoy you anymore ahah

i gave in input an .exe which i knew could not find a specific .dll: 

this is the .dll that the app does not find: MSVRC120.dll

![image](https://github.com/cgfandia/windep/assets/87523421/189b8335-f3ce-4317-a39c-1fd3c284199f)

but when i run windep.exe, i get the following result:

![image](https://github.com/cgfandia/windep/assets/87523421/ec4c75a5-c785-4b1e-a330-a03014824508)

this is the only one that results "unresolved: true"
why are there 2 different results?
Also, why does not me show the full path where .dll is expected?

**Comment by cgfandia** [comment] 2023-08-22 18:39
I'm not sure, but probably `rdpcoresccm.dll` depends on missed `msvrc120.dll`, and because of this windep cannot load it properly. I will check this case.
There is no expected path of the dependent DLL. OS is responsible for the search by DLL name.

**Comment by G0ne** [comment] 2023-08-22 20:26
thank you!
this tool looks nice, i was looking for something like that! simple, small, and from command line
to me, the only missing thing is an option to print just the missing .dll(s) rather then all

**Closed** 2023-08-23 18:10 UTC
